map_memory_node:
  ros__parameters:
    resolution: 0.1
    width: 1000
    height: 1000
    distance_threshold: 1.5
    cell_threshold: 50
    unknown_cell_value: -1

    costmap_topic: "/costmap"
    odom_topic: "/odom/filtered"
    map_topic: "/map"
    frame_id: "sim_world"