costmap:
  ros__parameters:
    resolution: 0.1
    width: 200
    height: 200
    inflation_radius: 1.0
    default_cell_value: 0
    max_cost_inflated_cell: 100
    cost_occupied: 100

    lidar_topic: "/lidar"
    costmap_topic: "/costmap"
    frame_id: "robot/chassis/lidar" # Use the same frame as the LaserScan